### ISSUE TITLE
Error on disable related to CommandAPI usage

### ISSUE THREAD

**Issue by lokka30** [ArcanePlugins/BlackWidow#18]
```
[6:59:25 ERROR]: [BlackWidow] +-------------------------------------------+
[16:59:25 ERROR]: [BlackWidow] 
[16:59:25 ERROR]: [BlackWidow] =----->Warning: Please Read Below Carefully
[16:59:25 ERROR]: [BlackWidow]  BlackWidow has detected an issue, please carefully read the below and attempt to resolve the issue (or otherwise, report it to the maintainers via the details also provided below).
[16:59:25 ERROR]: [BlackWidow] 
[16:59:25 ERROR]: [BlackWidow]  Sometimes, these are simple errors caused when users misconfigure the plugin, other times, it can be a bug (issue) with the plugin's code which the maintainers might not know about.
[16:59:25 ERROR]: [BlackWidow] 
[16:59:25 ERROR]: [BlackWidow] +-------------------------------------------+
[16:59:25 ERROR]: [BlackWidow] 
[16:59:25 ERROR]: [BlackWidow] =----->Details about this Issue
[16:59:25 ERROR]: [BlackWidow] Context (if known):
[16:59:25 ERROR]: [BlackWidow]  An error occurred whilst disabling BlackWidow.
[16:59:25 ERROR]: [BlackWidow] 
[16:59:25 ERROR]: [BlackWidow] Localized Message:
[16:59:25 ERROR]: [BlackWidow]  Tried to access CommandAPIHandler instance, but it was null! Are you using CommandAPI features before calling CommandAPI#onLoad?
[16:59:25 ERROR]: [BlackWidow] 
[16:59:25 ERROR]: [BlackWidow] +-------------------------------------------+
[16:59:25 ERROR]: [BlackWidow] 
[16:59:25 ERROR]: [BlackWidow] =----->Contacting Maintainers for Assistance
[16:59:25 ERROR]: [BlackWidow] If this is an issue you can't fix, or if it is a bug report, please contact the maintainers by checking for recommended links in the GitHub repository description.
[16:59:25 ERROR]: [BlackWidow] Please visit: < https://github.com/ArcanePlugins/BlackWidow/ >
[16:59:25 ERROR]: [BlackWidow] 
[16:59:25 ERROR]: [BlackWidow] Our Discord Server (should be linked within the page above) is usually the best avenue for users to report issues like these.
[16:59:25 ERROR]: [BlackWidow] 
[16:59:25 ERROR]: [BlackWidow] It's usually worth checking the Frequently Asked Questions page (if applicable).
[16:59:25 ERROR]: [BlackWidow] 
[16:59:25 ERROR]: [BlackWidow] +-------------------------------------------+
[16:59:25 ERROR]: [BlackWidow] 
[16:59:25 ERROR]: [BlackWidow] =----->Java Exception Details (for Developers)
[16:59:25 ERROR]: [BlackWidow] These details may be difficult to understand for those without Java experience.
[16:59:25 ERROR]: [BlackWidow] Regardless, it may contain useful details or expressions hinting to the root problem.
[16:59:25 ERROR]: [BlackWidow] 
[16:59:25 ERROR]: [BlackWidow] Exception Class:
[16:59:25 ERROR]: [BlackWidow]  IllegalStateException
[16:59:25 ERROR]: [BlackWidow] 
[16:59:25 ERROR]: [BlackWidow] Exception Stack Trace:
[16:59:25 WARN]: java.lang.IllegalStateException: Tried to access CommandAPIHandler instance, but it was null! Are you using CommandAPI features before calling CommandAPI#onLoad?
[16:59:25 WARN]:        at blackwidowpluginbukkit-1.1.0.jar//io.github.arcaneplugins.blackwidow.deps.dev.jorel.commandapi.CommandAPIHandler.getInstance(CommandAPIHandler.java:172)
[16:59:25 WARN]:        at blackwidowpluginbukkit-1.1.0.jar//io.github.arcaneplugins.blackwidow.deps.dev.jorel.commandapi.CommandAPI.getRegisteredCommands(CommandAPI.java:311)
[16:59:25 WARN]:        at blackwidowpluginbukkit-1.1.0.jar//io.github.arcaneplugins.blackwidow.plugin.bukkit.command.CommandManager.disable(CommandManager.java:61)
[16:59:25 WARN]:        at blackwidowpluginbukkit-1.1.0.jar//io.github.arcaneplugins.blackwidow.plugin.bukkit.BlackWidow.onDisable(BlackWidow.java:120)
[16:59:25 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:291)
[16:59:25 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:237)
[16:59:25 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugins(PaperPluginInstanceManager.java:161)
[16:59:25 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugins(PaperPluginManagerImpl.java:97)
[16:59:25 WARN]:        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:541)
[16:59:25 WARN]:        at org.bukkit.craftbukkit.CraftServer.disablePlugins(CraftServer.java:624)
[16:59:25 WARN]:        at net.minecraft.server.MinecraftServer.stopServer(MinecraftServer.java:1061)
[16:59:25 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.stopServer(DedicatedServer.java:793)
[16:59:25 WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1399)
[16:59:25 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:341)
[16:59:25 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[16:59:25 ERROR]: [BlackWidow] 
[16:59:25 ERROR]: [BlackWidow] +-------------------------------------------+
[16:59:25 ERROR]: [BlackWidow] 
[16:59:25 ERROR]: [BlackWidow] =----->ATTENTION Server Administrators:
[16:59:25 ERROR]: [BlackWidow] Just saw noticed the bottom of this log in your console? Don't panic - please scroll up to the top of this big log message and read carefully.
[16:59:25 ERROR]: [BlackWidow] 
[16:59:25 ERROR]: [BlackWidow] +-------------------------------------------+
```

Reported by `mnzasa` on the ArcanePlugins Discord. Reproduced by stumper66/PenalBuffalo. Need to debug why this is happening (after reproducing it myself).

**Comment by lokka30** [comment]
Resolved via v1.1.1 
https://www.spigotmc.org/resources/blackwidow-command-security.120751/update?update=572260
